// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeNXhdtp9A9wsRNGAfF0hhKZVS-otIXfs',
    appId: '1:855327470872:web:4761be6ae71deb2ce15a6d',
    messagingSenderId: '855327470872',
    projectId: 'verdantia-3752b',
    authDomain: 'verdantia-3752b.firebaseapp.com',
    storageBucket: 'verdantia-3752b.firebasestorage.app',
    measurementId: 'G-6C7H2MJC4N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKN8WKZhw7f3jYFIWHnyYgEExjwIsFfOI',
    appId: '1:855327470872:android:e9e2df105dee5d07e15a6d',
    messagingSenderId: '855327470872',
    projectId: 'verdantia-3752b',
    storageBucket: 'verdantia-3752b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdUg_h6ek0wqjeInEFNI_NzqmhM5cVbXE',
    appId: '1:855327470872:ios:265f16d8f81531aee15a6d',
    messagingSenderId: '855327470872',
    projectId: 'verdantia-3752b',
    storageBucket: 'verdantia-3752b.firebasestorage.app',
    iosBundleId: 'com.example.verdantia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdUg_h6ek0wqjeInEFNI_NzqmhM5cVbXE',
    appId: '1:855327470872:ios:265f16d8f81531aee15a6d',
    messagingSenderId: '855327470872',
    projectId: 'verdantia-3752b',
    storageBucket: 'verdantia-3752b.firebasestorage.app',
    iosBundleId: 'com.example.verdantia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAeNXhdtp9A9wsRNGAfF0hhKZVS-otIXfs',
    appId: '1:855327470872:web:301d3750ce8f15e6e15a6d',
    messagingSenderId: '855327470872',
    projectId: 'verdantia-3752b',
    authDomain: 'verdantia-3752b.firebaseapp.com',
    storageBucket: 'verdantia-3752b.firebasestorage.app',
    measurementId: 'G-S7S73SZYHS',
  );
}
